apiVersion: v1
kind: Secret
metadata:
    name: netlib
    namespace: netlib
type: Opaque
data:
    DATABASE_URL: ENC[AES256_GCM,data:EzXrkgS8BELub+ABWGD9PM+JoyRnsMkRBMFkeXSbgh+xRzn7/KZmXHwRnWXw5LWnoQfXQQ9wTySo5nqNRQNCDTdbqgsyT+X0aOnUfq5YngC858i1,iv:1Hu/EXqU77qxW0Et2N73OzO6e0AO/nIcTf/YKile07s=,tag:zA70VRtIQjuAN39Ce5CrpQ==,type:str]
    CLOUDFLARE_APP_ID: ENC[AES256_GCM,data:IA+zEzgowAwq/+y5Sg28pl95sjiKYiuPj9niKpik4OWmYyuDJTpz8WuYdY8=,iv:89F0Uf3/H0rV157gfQcrNxWW68HKGXLSqGQDkZtPKx8=,tag:JMPJrtbwOJAl305+Ys1KIA==,type:str]
    CLOUDFLARE_AUTH_KEY: ENC[AES256_GCM,data:g83DIidq5zfPJg1Z3S8OkbNxBli9I8XX/g0oxCTLMyIvYZKeTJ3RpjhC9NPJwOjnbvfx9GOJREc=,iv:bPGVMLBY4bpqX2mJZBdDeTsm8E4anlvBzStj4HwoJrM=,tag:ODjUsHXHQgTjkQnkJwwW4w==,type:str]
    METRICS_URL: ENC[AES256_GCM,data:s0JL5s6mT4seWFi7/4wu1itKS+NG3RbBKE7UEhmTAyI=,iv:/rcgu4RueZZGBhoKApe2OGQ3/XXFtD2h2e96OK6Q0co=,tag:T+pFAcWCpEoSYT8MTQmVwg==,type:str]
sops:
    gcp_kms:
        - resource_id: projects/poki-core/locations/global/keyRings/sops/cryptoKeys/mothership
          created_at: "2024-03-26T10:58:44Z"
          enc: CiQA1RLHUnCKI/I8HRYspex486GlBLy8bv2id3u18mOw62JOs+QSSQCh8/hAeJSfMVGrlOxzhhoXQjD81AOnsuyj3JgOzSOnmKAR5d4nLlkGBpu4O1ilHBjXF/EREFpOLS1sauhy5eSGwkCXcyMmO1o=
    lastmodified: "2025-09-03T10:12:42Z"
    mac: ENC[AES256_GCM,data:DBih4v2Cbx5lqqv9lEOZ4eNcYl+2Fzw472lOJ/NN820ZLaB4t6m2q559T94dQgERKf7FMG8Z8rKIxKuLHxGZWACoHOhlcJx3sDcwTA9mGk+UUn/B+SA15sLrxZxyUeo6JyvPxsh7Q9JLAHTYy88Xkm56Am/nsG4GZY746pyUzGY=,iv:0s+sYk3aQK13ayzCxddXbGEjuTuze2kRx1F7GaLCB0M=,tag:+gDcrIpEE3j9qiV1OtqwYg==,type:str]
    pgp:
        - created_at: "2024-03-26T10:58:44Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA1Dr/V7atjJPAQ//dsb7c4SXhleh7wWyi1g0B4knWRmUEvCjwG1T999eBdcX
            2B6n4GCoFqDUYKpsaNK7HAXvvIyZ2h6St1bU6n7vyNSZqgPQHMKjSY2u+F0OOYyf
            gm9M0Ahg3aoinNkCj2N7FCYUQ5LRPIWIcMSOZN+hzWRKXREzKE66xBTSlFr2RXHe
            oBU7jWftyF6bWryZYBY93e3edfQsIJZt8rKB1waPbQga+kFjb4hkImLMalERDbBc
            WsMN0xmvEqOLAwBNDzuWj2Xe0KhA2J3e0E2tlnzHtVaatwFJXv9/3HN8KVRRnSMy
            +TKE0dIQqmXar4q6yIuRCPmsG4+6H3Fc448JvQY6ck2hV1rmLFUmM9KZ2ucPCUKw
            HBBlNv00Hzj4vwSENyYo3zMBQIiANZ9Gbv8Ck11V2dCY/lUU9JGXMoJFAIq6f2OM
            hOMFr4TtwfHvJOLSdDU9vr3mTfqJpcnROxvBL+H6GxjWdENydU4dh78DR9ZzPTX0
            NByexYoXXVsgnXU3/E8jtK1AoOyOfiAUNKjMcsf0lbKSqlLQbQOgwC/KkUlJ6ll+
            GpqGQjanb2nIqP++/wfszM30ute15SlSbBEemliAgFJncjxunQUDPQ7oxkReDlD2
            tjTvSIzdrmCGNGsr7zoC/ZyeLZysv4YiNh4/WjJiSfX36aysrw9n9m3GsGFSB4jS
            VgGvVZL9QYDQOZTGfeW/vl95JBFpZtyVQlFrCT66uqeaxIHrmC9ngv39WbfKjo+L
            5oiKXwuPxMbKiygOkM2NPxVmbWlv/s6sXTsC6tmOvi/pkDbjG/B+
            =y5nt
            -----END PGP MESSAGE-----
          fp: A88D9578C2CBC1D29F33B03650EBFD5EDAB6324F
        - created_at: "2024-03-26T10:58:44Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQEMAxJ48vaOh15YAQgAoWnbOzxQMrX/5Mzc/CPPfP5Wfw3CjC9crIaQD/FEEqmJ
            nmPZUFb3JfscldXMvjGdGJeRfJS7HMey/0760uwgeyVxLYwGuLxmioXEkKX2nbDp
            fZDVJV3GTXQPCe2WbebdJp9QcPhP7l4DNT60RbkOMbq7DpPqJOEAzaKTh/nG5Cfq
            6qMb7HL08hWpRH1R/k5sQVZGPuB4DGa8U33AXxqMIC12WTAy/XS1Lr1hXT8S7VLG
            REy+nfVx3kkc5lcdhdp5dBr3MrPpesLsC82TL4HRiqU45DepEnGxbfKX7kt2cOWp
            D5pqdRRtL9SCHl5IAbOWLbY7vEqVbQa+9i+eFRGmdtJcAVFRtMp73jj/OadQ3UCD
            FVB2/6e1SDxsu5Gu5Sqxs1rb962YPD4pkZG6tbNULFqFqrfYknEe5GxURogw+Go4
            y8Qi6QuO3/YC2p+PWh0YQ7W0yG0/TU2L/YkoQRA=
            =WhGL
            -----END PGP MESSAGE-----
          fp: 85F01C37959ACAE487AD24BCA72A9A05A3DEABEC
    encrypted_regex: ^data$
    version: 3.10.2
