apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: netlib
spec:
  secretName: netlib-ssl
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - netlib.poki.io
