name: Build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: '1.24.0'
    - run: yarn install --frozen-lockfile
    - run: yarn lint
    - run: yarn cucumber
      env:
        DOCKER_HOST: unix:///var/run/docker.sock
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: GCP auth
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
    - name: 'Set up Cloud SDK'
      uses: google-github-actions/setup-gcloud@v2
    - name: Configure docker for GCP
      run: gcloud auth configure-docker europe-docker.pkg.dev
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: europe-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/netlib/signaling:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
  deploy:
    runs-on: ubuntu-latest
    needs:
    - build
    - test
    timeout-minutes: 30
    if: github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v4
    - name: GCP auth
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
    - name: 'Set up Cloud SDK'
      uses: google-github-actions/setup-gcloud@v2
    - uses: google-github-actions/get-gke-credentials@v2
      with:
        cluster_name: production-eu-west-4
        location: europe-west4-a
    - name: Install SOPS
      run: |-
        curl -LO https://github.com/getsops/sops/releases/download/v3.8.1/sops-v3.8.1.linux.amd64
        chmod +x sops-v3.8.1.linux.amd64
        sudo mv sops-v3.8.1.linux.amd64 /usr/local/bin/sops
    - name: Apply secrets
      run: sops --decrypt "manifest/secrets.yaml" | kubectl apply --validate -f -
    - name: Deploy
      run: kubectl kustomize "manifest" | envsubst | kubectl apply --validate -f -
