name: Build

on:
  pull_request:
  push:
    branches:
    - main

jobs:
  test:
    runs-on: hetzner
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v7
    - uses: actions/setup-go@v6
      with:
        go-version: '1.25.0'
        cache: false # Use the persistent self-hosted runner Go cache.
    - uses: actions/setup-node@v6
      with:
        node-version: 24
    - name: Enable Corepack
      run: corepack enable
    - run: yarn install --frozen-lockfile
    - run: yarn lint
    - run: yarn cucumber
      env:
        DOCKER_HOST: unix:///var/run/docker.sock
  golangci-lint:
    name: golangci-lint
    runs-on: hetzner
    steps:
    - uses: actions/setup-go@v6
      with:
        go-version: 1.26
        cache: false # Use the persistent self-hosted runner Go cache.
    - uses: actions/checkout@v7
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v9.2.1
      with:
        version: v2.10.1
  build:
    runs-on: hetzner
    timeout-minutes: 30
    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v4
    - name: GCP auth
      uses: google-github-actions/auth@v3
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
    - name: 'Set up Cloud SDK'
      uses: google-github-actions/setup-gcloud@v3
    - name: Configure docker for GCP
      run: gcloud auth configure-docker europe-docker.pkg.dev
    - name: Build and push
      uses: docker/build-push-action@v7.2.0
      with:
        push: true
        tags: europe-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/netlib/signaling:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
  deploy:
    runs-on: hetzner
    needs:
    - build
    - test
    - golangci-lint
    timeout-minutes: 30
    if: github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v7
    - name: GCP auth
      uses: google-github-actions/auth@v3
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
    - name: 'Set up Cloud SDK'
      uses: google-github-actions/setup-gcloud@v3
    - uses: google-github-actions/get-gke-credentials@v3
      with:
        cluster_name: production-eu-west-4
        location: europe-west4-a
    - name: Verify SOPS
      run: sops --version
    - name: Apply secrets
      run: sops --decrypt "manifest/secrets.yaml" | kubectl apply --validate -f -
    - name: Deploy
      run: kubectl kustomize "manifest" | envsubst | kubectl apply --validate -f -
