name: CI
on: push
env:
  DOCKER_HOST: unix:///var/run/docker.sock
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: '1.22.3'
    - run: go version
    - run: yarn
    - run: yarn lint
    - run: yarn cucumber
